- defaults:
    link:
      relink: true

- clean: ['~']

- link:
    ~/.tmux.conf: tmux
    ~/.vim: vim
    ~/.vimrc: vimrc

- create:
    - ~/.vim/undo-history

- shell:
  - [git submodule update --init --recursive, Installing submodules]
